first review
ShunaevN/stellar-burgers pull request #1
Opened 2024-12-22 16:55 UTC by ShunaevN

2024-12-22 19:26 UTC, aromanovnik requested changes
Добрый день, Никита!

Работа выполнена очень хорошо: конструктор бургеров работает стабильно, ингредиенты добавляются и отображается счётчик добавленных в конструктор. Авторизация и регистрация работают правильно. Лента заказов корректно отображает список, при клике на кнопку “Обновить” отправляется запрос за актуальными данными. Изменение данных пользователя также функционируют корректно, все модальные окна открываются с нужным URL. Код чистый, структурированный и читаемый. Отличная работа!

Тем не менее, есть несколько замечаний, которые потребуют доработки. Более подробно о них написано в комментариях к коду.

Что нужно исправить:
* По заданию, только авторизированные пользователи могут оформлять заказы. Если неавторизированный пользователь нажимает на кнопку «Оформить заказ», его должно перенаправлять на страницу входа. На данный момент данная логика отсутствует, требуется доработка.
* Навигация при закрытии на `navigate('/')` излишняя, так как оформление заказа уже выполняется на странице `/`.
* После заказа не закрывается модальное окно, это из за того, что присвоение переменной `state` нового значения `initialState` не меняет Redux-состояние. В Redux Toolkit применяется библиотека `Immer`, которая позволяет писать “мутабельный” код, но на самом деле сохраняет неизменяемость состояния. Для полного сброса состояния на initialState нужно использовать return в функции: `clearOrder: () => initialState`, либо изменять каждое поле по отдельности.
* На странице `/profile/orders` должен отображаться список заказов пользователя. В текущей реализации страница пуста, поэтому необходимо добавить функционал для загрузки и отображения заказов.
* После успешной авторизации должно происходить перенаправление на тот маршрут, который пользователь пытался посетить ранее. Для этого при переходе на страницу входа следует сохранять маршрут, с которого был перенаправлен пользователь, и при успешном входе перенаправлять его на сохранённый маршрут, если таковой имеется.

Что можно улучшить:
* В репозиторий стоит включать файл `.env.example` с пустыми или случайными значениями. Это поможет другим разработчикам быстро понять, какие переменные окружения требуются проекту, без необходимости изучать код в поисках всех используемых ключей.
* Очищать конструктор лучше сразу после успешного оформления заказа в `createAsyncThunk`, а не при закрытии модального окна с информацией о заказе. Такой подход позволит избежать ситуаций, когда конструктор остаётся заполненным при повторном открытии модального окна или при ошибках закрытия.
* Если в `createAsyncThunk` нужно просто вызвать функцию запроса и получить возвращаемое знание, без какой либо его обработки, то не нужно создавать функцию обертку. Лучше просто передать саму функцию запроса в качестве аргумента, например: `createAsyncThunk('ingredients/getIngredients', getIngredientsApi);`.
* Правильнее сделать отдельный селектор, чтобы изолировать логику доступа к данным состояния и избежать дублирования кода при доступе к данным в разных частях приложения. Это также позволяет легче изменять структуру состояния в будущем без необходимости вносить изменения во множество компонентов.

Напоминаю, что работа может быть принята только после исправления всех критических замечаний **Надо исправить**.

Удачного рефакторинга кода.

2024-12-22 19:26 UTC, aromanovnik commented on .env.example
> -BURGER_API_URL=https://norma.nomoreparties.space/api
**Можно лучше**: В репозиторий стоит включать файл `.env.example` с пустыми или случайными значениями. Это поможет другим разработчикам быстро понять, какие переменные окружения требуются проекту, без необходимости изучать код в поисках всех используемых ключей.

2024-12-22 19:26 UTC, aromanovnik commented on src/components/burger-constructor/burger-constructor.tsx
> +  const onOrderClick = useCallback(() => {
**Надо исправить**: По заданию, только авторизированные пользователи могут оформлять заказы. Если неавторизированный пользователь нажимает на кнопку «Оформить заказ», его должно перенаправлять на страницу входа. На данный момент данная логика отсутствует, требуется доработка.

<img width="1517" alt="Снимок экрана 2024-12-22 в 21 07 40" src="https://github.com/user-attachments/assets/9df93992-21ec-49e1-8077-09b7d85cf3be" />

2024-12-22 19:26 UTC, aromanovnik commented on src/components/burger-constructor/burger-constructor.tsx
> +    dispatch(clearConstructor());
**Можно лучше**: Очищать конструктор лучше сразу после успешного оформления заказа в `createAsyncThunk`, а не при закрытии модального окна с информацией о заказе. Такой подход позволит избежать ситуаций, когда конструктор остаётся заполненным при повторном открытии модального окна или при ошибках закрытия.

2024-12-22 19:26 UTC, aromanovnik commented on src/components/burger-constructor/burger-constructor.tsx
> +    navigate('/');
**Надо исправить**: Навигация при закрытии на `navigate('/')` излишняя, так как оформление заказа уже выполняется на странице `/`.

2024-12-22 19:26 UTC, aromanovnik commented on src/services/slices/newOrder/index.ts
> +    clearOrder: (state) => {
**Надо исправить**: После заказа не закрывается модальное окно, это из за того, что присвоение переменной `state` нового значения `initialState` не меняет Redux-состояние. В Redux Toolkit применяется библиотека `Immer`, которая позволяет писать “мутабельный” код, но на самом деле сохраняет неизменяемость состояния. Для полного сброса состояния на initialState нужно использовать return в функции: `clearOrder: () => initialState`, либо изменять каждое поле по отдельности.

<img width="1062" alt="Снимок экрана 2024-12-22 в 21 08 14" src="https://github.com/user-attachments/assets/2f0eb8cc-0f44-4b2f-8037-8a48f9f6cd7e" />

2024-12-22 19:26 UTC, aromanovnik commented on src/services/slices/ingridients/index.ts
> +export const getIngredients = createAsyncThunk(
**Можно лучше:** Если в `createAsyncThunk` нужно просто вызвать функцию запроса и получить возвращаемое знание, без какой либо его обработки, то не нужно создавать функцию обертку. Лучше просто передать саму функцию запроса в качестве аргумента, например: `createAsyncThunk('ingredients/getIngredients', getIngredientsApi);`

2024-12-22 19:26 UTC, aromanovnik commented on src/pages/profile-orders/profile-orders.tsx
> +  const orders = useSelector(getAllOrders);
**Надо исправить**: На странице `/profile/orders` должен отображаться список заказов пользователя. В текущей реализации страница пуста, поэтому необходимо добавить функционал для загрузки и отображения заказов.

<img width="1226" alt="Снимок экрана 2024-12-22 в 21 50 19" src="https://github.com/user-attachments/assets/162ad0de-f1db-4b5a-bf42-35353e373e83" />

2024-12-22 19:26 UTC, aromanovnik commented on src/pages/login/login.tsx
> +    navigate('/', { replace: true });
**Надо исправить**: После успешной авторизации должно происходить перенаправление на тот маршрут, который пользователь пытался посетить ранее. Для этого при переходе на страницу входа следует сохранять маршрут, с которого был перенаправлен пользователь, и при успешном входе перенаправлять его на сохранённый маршрут, если таковой имеется.

2024-12-22 19:26 UTC, aromanovnik commented on src/components/burger-constructor/burger-constructor.tsx
> +  const orderModalData = useSelector((state) => state.addBurder.orderModalData);
**Можно лучше**: Правильнее сделать отдельный селектор, чтобы изолировать логику доступа к данным состояния и избежать дублирования кода при доступе к данным в разных частях приложения. Это также позволяет легче изменять структуру состояния в будущем без необходимости вносить изменения во множество компонентов.

2024-12-23 07:35 UTC, ShunaevN commented on src/components/burger-constructor/burger-constructor.tsx
> +    dispatch(clearConstructor());
clearConstructor хранится в слайсе burgerConstructor, а createAsyncThunk на добавление бургера в слайсе newOrder. Получается нужно импортировать clearConstructor в слайс newOrder, что увеличит связанность компонентов или это ок?

2024-12-23 08:21 UTC, ShunaevN commented on src/components/burger-constructor/burger-constructor.tsx
> +  const orderModalData = useSelector((state) => state.addBurder.orderModalData);
Я изначально так и хотел и даже эти селекторы у меня есть  getOrderRequest: (state) => state.orderRequest,
    getOrderModalData: (state) => state.orderModalData, но они успешно подключаются в компоненте через useSelector только есть в слайсе я экспортирую редьюсер addBurgerSlice.reducer по дефолту. И проблема возникает почему-то в сторе в объекте rootReducer я не могу по ключу addBurder установить подходящее значение. Пробовал починить, не получилось, решил закостылить.

2024-12-23 11:56 UTC, aromanovnik commented on src/components/burger-constructor/burger-constructor.tsx
> +    dispatch(clearConstructor());
Например можно так: 

```
export const orderBurger = createAsyncThunk(
    'order/addBurger',
    (data: string[], {dispatch}) =>
        orderBurgerApi(data).then(({order}) => {
            dispatch(clearConstructor());
            return order;
        })
);
```

2024-12-23 12:03 UTC, aromanovnik approved these changes
Поздравляю! Ваша работа принята. Все недочеты исправлены. 

**Можно лучше**: Логика навигации уже реализована в компоненте `ProtectedRoute`, повторное использование на странице `login` избыточно.

Желаю успехов в дальнейшей учебе!

2024-12-23 12:03 UTC, aromanovnik commented on src/pages/login/login.tsx
> +    navigate(location.state?.from || { pathname: '/' });
**Можно лучше**: Логика навигации уже реализована в компоненте `ProtectedRoute`, повторное использование здесь избыточно.

2025-02-05 17:42 UTC, merged